///////////////////////////////////////////////////////////////////////////////
// SmartControllerModuleTaskClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "SmartControllerModuleTaskClassFactory.h"
#include "SmartControllerModuleTaskServices.h"
#include "SmartControllerModuleTaskVersion.h"
#include "TaskModule.h"

BEGIN_CLASS_MAP(CSmartControllerModuleTaskClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_SmartControllerModuleTaskCTaskModule, SRVNAME_SMARTCONTROLLERMODULETASK "!CTaskModule", CTaskModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CSmartControllerModuleTaskClassFactory::CSmartControllerModuleTaskClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_SMARTCONTROLLERMODULETASK)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(SmartControllerModuleTask));
#endif //defined(TCDBG_UNIT_VERSION)
}

