///////////////////////////////////////////////////////////////////////////////
// SmartControllerModuleTaskInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "SmartControllerModuleTaskServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
